- name: Deploy via rsync
  uses: burnett01/rsync-deployments@5.2
  with:
    switches: -avzr --delete
    path: ./
    remote_path: /var/www/test-deploy/
    remote_host: ${{ secrets.HOST }}
    remote_user: ${{ secrets.USER }}
    remote_key: ${{ secrets.KEY }}
